services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: voucher-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    command: npm run start
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    container_name: voucher-frontend
    env_file:
      - ./frontend-next/.env.docker
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - NODE_ENV=production
    command: node server.js
    restart: unless-stopped

networks:
  default:
    driver: bridge
